(function(g){var b=function(a,e,c){return 1===arguments.length?b.get(a):b.set(a,e,c)};b._document=document;b._navigator=navigator;b.defaults={path:"/"};b.get=function(a){b._cachedDocumentCookie!==b._document.cookie&&b._renewCache();return b._cache[a]};b.set=function(a,e,c){c=b._getExtendedOptions(c);c.expires=b._getExpiresDate(e===g?-1:c.expires);b._document.cookie=b._generateCookieString(a,e,c);return b};b.expire=function(a,e){return b.set(a,g,e)};b._getExtendedOptions=function(a){return{path:a&&
a.path||b.defaults.path,domain:a&&a.domain||b.defaults.domain,expires:a&&a.expires||b.defaults.expires,secure:a&&a.secure!==g?a.secure:b.defaults.secure}};b._isValidDate=function(a){return"[object Date]"===Object.prototype.toString.call(a)&&!isNaN(a.getTime())};b._getExpiresDate=function(a,e){e=e||new Date;switch(typeof a){case "number":a=new Date(e.getTime()+1E3*a);break;case "string":a=new Date(a)}if(a&&!b._isValidDate(a))throw Error("`expires` parameter cannot be converted to a valid Date instance");
return a};b._generateCookieString=function(a,b,c){a=a.replace(/[^#$&+\^`|]/g,encodeURIComponent);a=a.replace(/\(/g,"%28").replace(/\)/g,"%29");b=(b+"").replace(/[^!#$&-+\--:<-\[\]-~]/g,encodeURIComponent);c=c||{};a=a+"="+b+(c.path?";path="+c.path:"");a+=c.domain?";domain="+c.domain:"";a+=c.expires?";expires="+c.expires.toUTCString():"";return a+=c.secure?";secure":""};b._getCookieObjectFromString=function(a){var e={};a=a?a.split("; "):[];for(var c=0;c<a.length;c++){var d=b._getKeyValuePairFromCookieString(a[c]);
e[d.key]===g&&(e[d.key]=d.value)}return e};b._getKeyValuePairFromCookieString=function(a){var b=a.indexOf("="),b=0>b?a.length:b;try{return{key:decodeURIComponent(a.substr(0,b)),value:decodeURIComponent(a.substr(b+1))}}catch(c){return{key:a.substr(0,b),value:a.substr(b+1)}}};b._renewCache=function(){b._cache=b._getCookieObjectFromString(b._document.cookie);b._cachedDocumentCookie=b._document.cookie};b._areEnabled=function(){var a="1"===b.set("cookies.js",1).get("cookies.js");b.expire("cookies.js");
return a};b.enabled=b._areEnabled();"undefined"===typeof _lmt&&(window._lmt={});_lmt.cookies=b})();(function(g){var b=navigator.appVersion,a=navigator.userAgent,e=navigator.appName,c=""+parseFloat(navigator.appVersion),d=parseInt(navigator.appVersion,10),f,m;-1!=(f=a.indexOf("Opera"))?(e="Opera",c=a.substring(f+6),-1!=(f=a.indexOf("Version"))&&(c=a.substring(f+8))):-1!=(f=a.indexOf("MSIE"))?(e="Microsoft Internet Explorer",c=a.substring(f+5)):-1!=(f=a.indexOf("Chrome"))?(e="Chrome",c=a.substring(f+7)):-1!=(f=a.indexOf("Safari"))?(e="Safari",c=a.substring(f+7),-1!=(f=a.indexOf("Version"))&&(c=a.substring(f+
8))):-1!=(f=a.indexOf("Firefox"))?(e="Firefox",c=a.substring(f+8)):-1!=a.indexOf("Trident/")?(e="Microsoft Internet Explorer",c=a.substring(a.indexOf("rv:")+3)):(d=a.lastIndexOf(" ")+1)<(f=a.lastIndexOf("/"))&&(e=a.substring(d,f),c=a.substring(f+1),e.toLowerCase()==e.toUpperCase()&&(e=navigator.appName));-1!=(m=c.indexOf(";"))&&(c=c.substring(0,m));-1!=(m=c.indexOf(" "))&&(c=c.substring(0,m));-1!=(m=c.indexOf(")"))&&(c=c.substring(0,m));d=parseInt(""+c,10);isNaN(d)&&(c=""+parseFloat(navigator.appVersion),
parseInt(navigator.appVersion,10));m=/Mobile|mini|Fennec|Android|iP(ad|od|hone)/.test(b);d=navigator.cookieEnabled?!0:!1;"undefined"!=typeof navigator.cookieEnabled||d||(document.cookie="testcookie",document.cookie.indexOf("testcookie"));d="-";f=[{s:"Windows 3.11",r:/Win16/},{s:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},{s:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},{s:"Windows 98",r:/(Windows 98|Win98)/},{s:"Windows CE",r:/Windows CE/},{s:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{s:"Windows XP",
r:/(Windows NT 5.1|Windows XP)/},{s:"Windows Server 2003",r:/Windows NT 5.2/},{s:"Windows Vista",r:/Windows NT 6.0/},{s:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{s:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{s:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{s:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{s:"Windows ME",r:/Windows ME/},{s:"Android",r:/Android/},{s:"Open BSD",r:/OpenBSD/},{s:"Sun OS",r:/SunOS/},{s:"Linux",r:/(Linux|X11)/},{s:"iOS",r:/(iPhone|iPad|iPod)/},{s:"Mac OS X",
r:/Mac OS X/},{s:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{s:"QNX",r:/QNX/},{s:"UNIX",r:/UNIX/},{s:"BeOS",r:/BeOS/},{s:"OS/2",r:/OS\/2/},{s:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}];for(var h in f){var r=f[h];if(r.r.test(a)){d=r.s;break}}h="-";try{switch(/Windows/.test(d)&&(h=/Windows (.*)/.exec(d)[1],d="Windows"),d){case "Mac OS X":h=/Mac OS X (10[\.\_\d]+)/.exec(a)[1];break;case "Android":h=/Android ([\.\_\d]+)/.exec(a)[1];break;
case "iOS":h=/OS (\d+)_(\d+)_?(\d+)?/.exec(b),h=h[1]+"."+h[2]+"."+(h[3]|0)}}catch(t){}"undefined"===typeof _lmt&&(g._lmt={});_lmt.jscd={browser:e,browserVersion:c,mobile:m,os:d,osVersion:h}})(this);/*
 MIT  * @link http://www.freelancephp.net/domready-javascript-object-cross-browser/
 @link https://github.com/freelancephp/DOMReady
*/
(function(g){var b=g.document,a=[],e=[],c=!1,d=null,f=function(a){try{a.apply(this,e)}catch(b){null!==d&&d.call(this,b)}},m=function(){var b;c=!0;for(b=0;b<a.length;b+=1)f(a[b]);a=[]},h=function(a){return h.on(a)};h.on=function(b){c?f(b):a[a.length]=b;return this};h.params=function(a){e=a;return this};h.error=function(a){d=a;return this};(function(){if(g.addEventListener)b.addEventListener("DOMContentLoaded",function(){m()},!1);else{var a=function(){if(b.uniqueID||!b.expando){var c=b.createElement("document:ready");
try{c.doScroll("left"),m()}catch(e){g.setTimeout(a,10)}}};b.onreadystatechange=function(){"complete"===b.readyState&&(b.onreadystatechange=null,m())};a()}})();g._lmt=g._lmt||{};g._lmt.domReady=h})(window);(function(g){var b="",a={},e={},c=!1,d=function(a){return"undefined"===typeof a||null===a||0===a.length},f=_lmt.cookies,m=function(a){var b=new Image;b.onload=function(){};b.src=a;return b},h=function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return function(){return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}}(),r=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,t=function(a,b){"string"===typeof a&&a.match(r)||(a=h());f("_lmt_guid",a,{expires:63072E4});
b&&w(a)},w=function(a){m("https://t-bdp.yixin.com/img/_.gif?guid={guid}".replace("{guid}",a))},z=function(){try{var a=document.referrer;if(a.match(/^https?:\/\/(www|m).baidu.com\//i))for(var b=a.split(/[&\?]/),a=0;a<b.length;a++){var c=b[a].split("=");if(2<=c.length&&"wd"==c[0]|"word"==c[0])return c[1]}return null}catch(e){return null}},v=[],s=function(x,e){if(c){var d="https://t1-bdp.yixin.com/"+b+"/"+x+"?",p=f("_lmt_utm");"string"!==typeof p&&(p="");for(var u=p,g=document.location.search.replace(/^\?/,
"").split("&"),n=0;n<g.length;n+=1)g[n].match(/^utm_/)&&(u+="&"+g[n]);for(var g=u.split("&"),k={},n=0;n<g.length;n+=1){var r=g[n].split("=");2<=r.length&&(k[r[0]]=r[1])}if(u!==p){(p=z())&&(k.bd_wd=p);var p=[],l;for(l in k)p.push(l+"="+k[l]);f("_lmt_utm",p.join("&"),{expires:5184E3})}k.guid=f("_lmt_guid");l=f("_lmt_sid");if("undefined"===typeof l||0===l.length)l=h();f("_lmt_sid",l,{expires:1800});k.sessionid=l;l="";"undefined"!==typeof window.innerWidth&&"undefined"!==typeof window.innerHeight&&(l=
window.innerWidth+"x"+window.innerHeight);k.viewport=l;l="";"object"===typeof window.screen&&"undefined"!==typeof window.screen.width&&"undefined"!==typeof window.screen.height&&(l=window.screen.width+"x"+window.screen.height);k.screenresolution=l;k.host=document.location.host;k.localts=(new Date).getTime();k.os=_lmt.jscd.os;try{k.dreferrer=document.referrer||""}catch(t){}for(var q in a)k[q]=a[q];for(q in e)k[q]=e[q];for(var s in k)q=k[s],"undefined"!==typeof q&&(l=q,s.match(/^(utm|bd)_.*/)||(l=encodeURIComponent(q)),
d+=encodeURIComponent(s)+"="+l+"&");m(d)}else v.push([x,e])},y=function(a,b){"undefined"===typeof b&&(b={});"undefined"===typeof b.page&&(b.page=document.location.pathname+document.location.search+document.location.hash);s(a,b)},A=function(a,b){var c=a.getAttribute("data-lmt-track-trigger"),c=c?c.trim():"";if("click"===c){var e=a.onclick;a.onclick=function(){var c=b(),f=!0;"function"==typeof e&&!1===e()&&(f=!1);var g=a.getAttribute("href");return d(c)||d(g)||!f||(c=parseInt(c),isNaN(c))?f:(setTimeout(function(){document.location=
g},c),!1)}}else"change"===c?(e=a.onchange,a.onchange=function(){b();"function"===typeof e&&e()}):b()},B=function(a){var b=Array.prototype.slice.call(arguments).slice(1);return function(){var c=b.concat(Array.prototype.slice.call(arguments));return a.apply(this,c)}},C=function(a){for(var b=a.getAttribute("data-lmt-track-id"),c=a.getAttribute("data-lmt-track-data"),b=b?b.trim():"",c=c?c.split(";"):[],f=0;f<c.length;f+=1){var d={};try{d=JSON.parse(c[f].trim())}catch(g){d={}}if("event"in d){var h=d.event.trim(),
d=d.data;"object"!==typeof d&&(d={});!b||"lmt-track-id"in d||(d["lmt-track-id"]=b);if("sessionstart"===h&&"session-name"in d){var k=d["session-name"];e[k]=(new Date).getTime()}"sessionend"===h&&"session-name"in d&&(k=d["session-name"],k in e&&(d["session-duration"]=(new Date).getTime()-e[k]));"change"===h&&(k=a.value,"undefined"!==typeof k&&(d.value=k));y(h,d)}}return a.getAttribute("data-lmt-track-jump-wait")};"undefined"===typeof _lmt&&(window._lmt={});String.prototype.trim||function(){var a=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
String.prototype.trim=function(){return this.replace(a,"")}}();_lmt.trackPageView=function(a){0===arguments.length&&(a=document.location.pathname+document.location.search+document.location.hash);s("pageload",{page:a})};_lmt.trackEvent=y;_lmt.autoTrack=function(){_lmt&&_lmt.domReady&&_lmt.domReady(function(){for(var a=document.querySelectorAll?document.querySelectorAll("[data-lmt-track-data]"):[],b=0;b<a.length;b+=1){var c=a[b];A(c,B(C,c))}})};_lmt.setAppId=function(a){b=a};_lmt.setDomain=function(a){f.defaults.domain=
a};_lmt.setCommonData=function(b,c){a[b]=c};(function(){var a=f("_lmt_guid");if("undefined"===typeof a||0===a.length){var a=document.createElement("script"),b="_lmt_cb"+(new Date).getTime();window[b]=function(a){try{t(a,!0)}catch(b){t(null,!0)}};a.type="text/javascript";a.src="https://t-bdp.yixin.com/jsonp/guid?cb="+b;a.async=!1;var d=function(){for(c=!0;0<v.length;){var a=v.shift();s(a[0],a[1])}};a.onload=d;a.onreadystatechange=function(){"loaded"==this.readyState&&d()};document.getElementsByTagName("head")[0].insertBefore(a,
null)}else c=!0,w(a)})()})();
